params ["_display"];

_comboBox = _display displayctrl 2100;

_comboBox lbAdd "--- BASIC ---";
_comboBox lbAdd "Platoon";
_comboBox lbAdd "Alpha";
_comboBox lbAdd "Bravo";
_comboBox lbAdd "Charlie";
_comboBox lbAdd "Delta";
_comboBox lbAdd "--- SUPPORT ---";
_comboBox lbAdd "Enigneering";
_comboBox lbAdd "Medevac";
_comboBox lbAdd "Medical";
_comboBox lbAdd "Logistics";
_comboBox lbAdd "--- SPECIALIZED ---";
_comboBox lbAdd "Artillery";
_comboBox lbAdd "EOD 1";
_comboBox lbAdd "EOD 2";
_comboBox lbAdd "HAT 1";
_comboBox lbAdd "HAT 2";
_comboBox lbAdd "MAT 1";
_comboBox lbAdd "MAT 2";
_comboBox lbAdd "MMG 1";
_comboBox lbAdd "MMG 2";
_comboBox lbAdd "Mortar 1";
_comboBox lbAdd "Mortar 2";
_comboBox lbAdd "Recon 1";
_comboBox lbAdd "Recon 2";
_comboBox lbAdd "TACP";
_comboBox lbAdd "--- ARMOR ---";
_comboBox lbAdd "Archer";
_comboBox lbAdd "Anvil";
_comboBox lbAdd "Bulldog";
_comboBox lbAdd "Crusader";
_comboBox lbAdd "Hammer";
_comboBox lbAdd "Linebacker";
_comboBox lbAdd "Spartan";
_comboBox lbAdd "Thor";
_comboBox lbAdd "Thunder";
_comboBox lbAdd "Warpig";
_comboBox lbAdd "--- AIR ---";
_comboBox lbAdd "Blackbird";
_comboBox lbAdd "Bluejay";
_comboBox lbAdd "Cobra";
_comboBox lbAdd "Falcon";
_comboBox lbAdd "Hornet";
_comboBox lbAdd "Iceman";
_comboBox lbAdd "Maverick";
_comboBox lbAdd "Nimrod";
_comboBox lbAdd "Podracer";
_comboBox lbAdd "Sparrow";